import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { toast } from 'react-toastify';
import { poAPI } from '../../services/api';
import { PurchaseOrder } from '../../types';
import { StatusBadge, Spinner, PageHeader, InfoRow, fmt } from '../../components/common/SharedComponents';
import { useAuth } from '../../context/AuthContext';

const PODetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { isManager, isAdmin } = useAuth();
  const [po, setPO] = useState<PurchaseOrder | null>(null);
  const [loading, setLoading] = useState(true);
  const [updatingStatus, setUpdatingStatus] = useState(false);

  useEffect(() => {
    poAPI.getById(Number(id))
      .then(r => setPO(r.data.data))
      .catch(() => toast.error('Failed to load PO'))
      .finally(() => setLoading(false));
  }, [id]);

  const updateStatus = async (status: string) => {
    setUpdatingStatus(true);
    try {
      const res = await poAPI.updateStatus(Number(id), status);
      setPO(res.data.data);
      toast.success(`Status updated to ${status}`);
    } catch (err: any) { toast.error(err.response?.data?.message || 'Update failed'); }
    finally { setUpdatingStatus(false); }
  };

  const exportPdf = async () => {
    try {
      const res = await poAPI.exportPdf(Number(id));
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const a = document.createElement('a'); a.href = url; a.download = `${po?.poNumber}.pdf`; a.click();
      window.URL.revokeObjectURL(url);
    } catch { toast.error('Export failed'); }
  };

  if (loading) return <Spinner />;
  if (!po) return <div>Purchase Order not found</div>;

  const nextStatus: Record<string, string> = { GENERATED: 'SENT', SENT: 'RECEIVED', RECEIVED: 'CLOSED' };

  return (
    <div>
      <PageHeader title="Purchase Order"
        breadcrumb={[{ label: 'Purchase Orders', href: '/purchase-orders' }, { label: po.poNumber }]}
        actions={
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-secondary btn-sm" onClick={exportPdf}>
              <i className="bi bi-file-pdf" /> Export PDF
            </button>
            {(isManager || isAdmin) && nextStatus[po.status] && (
              <button className="btn btn-primary btn-sm" onClick={() => updateStatus(nextStatus[po.status])} disabled={updatingStatus}>
                <i className="bi bi-arrow-right-circle" /> Mark as {nextStatus[po.status]}
              </button>
            )}
          </div>
        } />

      <div style={{ display: 'flex', gap: 10, marginBottom: 20 }}>
        <span className="code-text">{po.poNumber}</span>
        <StatusBadge status={po.status} />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 16 }}>
        <div>
          {/* Main PO card */}
          <div className="card" style={{ marginBottom: 16 }}>
            <div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span style={{ fontWeight: 800, fontSize: '1.1rem' }}>PURCHASE ORDER</span>
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontWeight: 700, color: '#3b82f6' }}>{po.poNumber}</div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>Generated: {fmt.datetime(po.generatedAt)}</div>
              </div>
            </div>
            <div className="card-body">
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                <div style={{ background: 'var(--surface2)', borderRadius: 10, padding: 14 }}>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: 4 }}>VENDOR</div>
                  <div style={{ fontWeight: 700 }}>{po.vendorName}</div>
                </div>
                <div style={{ background: 'var(--surface2)', borderRadius: 10, padding: 14 }}>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: 4 }}>SHIP TO</div>
                  <div style={{ fontWeight: 600, fontSize: '0.875rem', lineHeight: 1.4 }}>{po.shippingAddress || '—'}</div>
                </div>
              </div>

              <InfoRow label="RFQ Reference" value={<Link to={`/rfqs/${po.rfqId}`} style={{ textDecoration: 'none' }}><span className="code-text">{po.rfqNumber}</span></Link>} />
              <InfoRow label="Delivery Date" value={<strong>{fmt.date(po.deliveryDate)}</strong>} />
              <InfoRow label="Payment Terms" value={po.paymentTerms || '—'} />
              <InfoRow label="Generated By" value={po.generatedByName} />
              {po.specialInstructions && (
                <div style={{ marginTop: 12 }}>
                  <div style={{ fontSize: '0.82rem', color: 'var(--text-muted)', marginBottom: 4 }}>Special Instructions</div>
                  <div style={{ background: 'rgba(245,158,11,0.08)', borderLeft: '3px solid #f59e0b', padding: '8px 12px', borderRadius: '0 8px 8px 0', fontSize: '0.875rem' }}>
                    {po.specialInstructions}
                  </div>
                </div>
              )}
            </div>
            <div style={{ padding: '14px 20px', borderTop: '2px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>Total Order Value</span>
              <span style={{ fontWeight: 800, fontSize: '1.6rem', color: '#3b82f6' }}>
                {fmt.currency(po.totalAmount, po.currency)}
              </span>
            </div>
          </div>
        </div>

        {/* Status tracker */}
        <div className="card">
          <div className="card-header">Order Status</div>
          <div className="card-body">
            {['GENERATED','SENT','RECEIVED','CLOSED'].map((s, i) => {
              const statuses = ['GENERATED','SENT','RECEIVED','CLOSED'];
              const currentIdx = statuses.indexOf(po.status);
              const done = i <= currentIdx;
              return (
                <div key={s} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: i < 3 ? 12 : 0 }}>
                  <div style={{
                    width: 32, height: 32, borderRadius: '50%', border: `2px solid ${done ? '#22c55e' : 'var(--border)'}`,
                    background: done ? '#22c55e' : 'transparent',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: done ? '#fff' : 'var(--text-muted)', fontSize: '0.8rem', fontWeight: 700, flexShrink: 0,
                  }}>
                    {done ? <i className="bi bi-check-lg" /> : i + 1}
                  </div>
                  <div>
                    <div style={{ fontWeight: i === currentIdx ? 700 : 500, fontSize: '0.875rem', color: i === currentIdx ? 'var(--text)' : 'var(--text-muted)' }}>{s}</div>
                    {i === currentIdx && <div style={{ fontSize: '0.72rem', color: '#22c55e' }}>● Current</div>}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
};

export default PODetailPage;
