import React, { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'react-toastify';
import { poAPI } from '../../services/api';
import { PurchaseOrder, POStatus } from '../../types';
import { StatusBadge, Pagination, Spinner, EmptyState, PageHeader, fmt } from '../../components/common/SharedComponents';

const POListPage: React.FC = () => {
  const [pos, setPOs] = useState<PurchaseOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<POStatus | ''>('');
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [total, setTotal] = useState(0);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await poAPI.getAll({ status: statusFilter || undefined, page, size: 10 });
      const d = res.data.data;
      setPOs(d.content); setTotalPages(d.totalPages); setTotal(d.totalElements);
    } catch { toast.error('Failed to load purchase orders'); }
    finally { setLoading(false); }
  }, [statusFilter, page]);

  useEffect(() => { load(); }, [load]);

  const exportPdf = async (id: number, poNum: string) => {
    try {
      const res = await poAPI.exportPdf(id);
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const a = document.createElement('a'); a.href = url; a.download = `${poNum}.pdf`; a.click();
      window.URL.revokeObjectURL(url);
    } catch { toast.error('Export failed'); }
  };

  return (
    <div>
      <PageHeader title="Purchase Orders" subtitle={`${total} total`} />
      <div className="filter-bar">
        <select className="form-control form-select" style={{ width: 180 }} value={statusFilter}
          onChange={e => { setStatusFilter(e.target.value as any); setPage(0); }}>
          <option value="">All Statuses</option>
          {['GENERATED','SENT','RECEIVED','CLOSED'].map(s => <option key={s} value={s}>{s}</option>)}
        </select>
      </div>
      <div className="table-wrapper">
        {loading ? <Spinner /> : pos.length === 0 ? (
          <EmptyState icon="bi-bag-check" title="No purchase orders" desc="POs are generated after awarding RFQs" />
        ) : (
          <>
            <div style={{ overflowX: 'auto' }}>
              <table className="table">
                <thead>
                  <tr><th>PO Number</th><th>RFQ</th><th>Vendor</th><th>Total Amount</th><th>Delivery Date</th><th>Status</th><th>Generated By</th><th>Generated At</th><th>Actions</th></tr>
                </thead>
                <tbody>
                  {pos.map(po => (
                    <tr key={po.id}>
                      <td><span className="code-text">{po.poNumber}</span></td>
                      <td><Link to={`/rfqs/${po.rfqId}`} style={{ textDecoration: 'none' }}><span className="code-text">{po.rfqNumber}</span></Link></td>
                      <td style={{ fontWeight: 600, fontSize: '0.875rem' }}>{po.vendorName}</td>
                      <td style={{ fontWeight: 700, color: '#3b82f6' }}>{fmt.currency(po.totalAmount, po.currency)}</td>
                      <td style={{ fontSize: '0.82rem' }}>{fmt.date(po.deliveryDate)}</td>
                      <td><StatusBadge status={po.status} /></td>
                      <td style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>{po.generatedByName}</td>
                      <td style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>{fmt.datetime(po.generatedAt)}</td>
                      <td>
                        <div style={{ display: 'flex', gap: 4 }}>
                          <Link to={`/purchase-orders/${po.id}`} className="btn btn-outline-primary btn-sm btn-icon"><i className="bi bi-eye" /></Link>
                          <button className="btn btn-secondary btn-sm btn-icon" title="Export PDF" onClick={() => exportPdf(po.id, po.poNumber)}><i className="bi bi-file-pdf" /></button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', borderTop: '1px solid var(--border)' }}>
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Showing {page * 10 + 1}–{Math.min((page + 1) * 10, total)} of {total}</span>
              <Pagination page={page} total={totalPages} onChange={setPage} />
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default POListPage;
